### ISSUE TITLE
Opening in web not working

### ISSUE THREAD

**Issue by fnandoz21** [victorbalssa/expo-ticket-app#2]
Hi I am trying to use your boilerplate to create an app that will run on iOS, Android, and on a web browser. However, when I try to run the web browser option on Expo, I am met with the following error:

[***path to app folder***]/node_modules/react-native-web/dist/exports/createElement/index.js
Module not found: Can't resolve 'react-dom/unstable-native-dependencies' in '[***path to app folder***]\node_modules\react-native-web\dist\exports\createElement'

I am running this on a Windows computer, in case that makes a difference. Also, it works fine for the mobile versions, just not on web.

**Comment by victorbalssa** [comment]
Ok I'm sorry right now, this repository, is design to work on Mobile environment only.
But if you want to add web react part (I don't recommend expo-web as it is not stable yet) you can contribute and add Pull request,

Victor
