### ISSUE TITLE
Firebase sample event not showing up in app

### ISSUE THREAD

**Issue by fnandoz21** [victorbalssa/expo-ticket-app#3]
I just followed your instructions to load in the sample data into the Firebase but I cannot find the sample event from your article anywhere in the app. Could you perhaps detail this process a bit more so I can troubleshoot?

**Comment by victorbalssa** [comment]
Hi thanks for contributing!
the sample event is here ->https://github.com/victorbalssa/expo-ticket-app/blob/master/events-export.json

You need to import JSON data directly info realtime database at `/events` 

Let me know if you have issues doing this
